---

services:
  proxy:
    image: ghcr.io/applicreation/harmony-proxy:v0
    ports:
      - 80:80
  core:
    image: ghcr.io/applicreation/harmony-core:v0
    restart: on-failure
    env_file:
      - ./.harmony/core/.env
    volumes:
      - ./.harmony/core:/root/.harmony:ro
  docs:
    image: node:lts-alpine
    command:
      - npm
      - run
      - dev
    working_dir: /app
    env_file:
      - ./.harmony/docs/.env
    volumes:
      - ./.harmony/docs:/root/.harmony:ro
      - ./app:/app
